ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/ap3220
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include/
obj-y += ap3220.o
obj-y += bbk_alsps.o

