#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += nt35521s_wxga_dsi_vdo_boe.o lcm_vendor_debug.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/video/mt8167/videox


