#
LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := H5000

MODULES += app/mt_boot \
           dev/lcm

MTK_EMMC_SUPPORT = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
MTK_KERNEL_POWER_OFF_CHARGING = yes
#DEFINES += SWCHR_POWER_PATH
#DEFINES += MTK_BQ24261_SUPPORT
MTK_LCM_PHYSICAL_ROTATION = 0
CUSTOM_LK_LCM="nt35521s_wxga_dsi_vdo_boe fiti_jd9365_wxga_dsi_vdo_inno fiti_jd9364_wxga_dsi_vdo_boe"
#nt35595_fhd_dsi_cmd_truly_nt50358 = yes

#FASTBOOT_USE_G_ORIGINAL_PROTOCOL = yes
MTK_SECURITY_SW_SUPPORT = yes
MTK_VERIFIED_BOOT_SUPPORT = yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes

BOOT_LOGO=wxga

#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1

MTK_IN_HOUSE_TEE_SUPPORT=yes
MTK_SEC_VIDEO_PATH_SUPPORT=yes
MTK_WVDRM_L1_SUPPORT = no
